### ISSUE TITLE
Question - What is nguniversal/express-engine Used for?

### ISSUE THREAD

**Issue by Adam-Kernig** [salemdar/ngx-cookie#101]
Hi, I'm new to angular

Im just trying to find out why there is a dependancy for this in the package - can anyone help me understand?

Thank you

**Comment by crhistianramirez** [comment]
Its used for server side rendering. Not really necessary for most apps and it looks like there's an issue to refactor the app to remove the dependency: https://github.com/salemdar/ngx-cookie/issues/79

I think this project is dead though 🙁

**Comment by salemdar** [comment]
I divided the modules into different packages, rearranged peer dependencies. This shouldn't be a problem anymore.
