### ISSUE TITLE
ngx-cookies SSR

### ISSUE THREAD

**Issue by vitaliyzolotoy** [salemdar/ngx-cookie#104]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
During using ngx-cookies with my SSR app this.cookieService.get() on server side returns "undefined"

**Expected/desired behavior**
Getting cookie on server side

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-cookie version:** 4.1.2

* **Angular version:** 7.2.11
 
* **Browser:** [all]

**Comment by free-easy** [comment]
It's caused by this line

https://github.com/salemdar/ngx-cookie/blob/7c97205c4be1eeb8f23f663675c240d22f9b5a74/lib/src/lib/cookie-backend.service.ts#L17

There's no `cookie` property on the request object of express.js. `headers.cookie` should be used.

**Comment by crhistianramirez** [comment]
You might just be able to add [cookie-parser](https://expressjs.com/en/api.html#req.cookies)

**Comment by rkajbaf** [comment]
As a work around, u can do this in your server.ts

```
// All regular routes use the Universal engine
app.get('*', (req, res) => {
  req.cookie = req.headers.cookie;
  res.render('index', {
    req: req,
    res: res,
    providers: [
      {
        provide: 'REQUEST',
        useValue: (req)
      },
      {
        provide: 'RESPONSE', useValue: (res)
      }
    ]
  });
});
```

Specifically, this line:

`req.cookie = req.headers.cookie;`

Will get it working.

**Comment by kryne** [comment]
> As a work around, u can do this in your server.ts
> 
> ```
> // All regular routes use the Universal engine
> app.get('*', (req, res) => {
>   req.cookie = req.headers.cookie;
>   res.render('index', {
>     req: req,
>     res: res,
>     providers: [
>       {
>         provide: 'REQUEST',
>         useValue: (req)
>       },
>       {
>         provide: 'RESPONSE', useValue: (res)
>       }
>     ]
>   });
> });
> ```
> 
> Specifically, this line:
> 
> `req.cookie = req.headers.cookie;`
> 
> Will get it working. The rest of the code is exactly the same as the example they use in their getting started guide.

they should add this in the documentation

**Comment by kuncevic** [comment]
With the latest universal SSR had to fix similar problem this way:
```
  server.get('*', (req, res) => {
    req.cookies = req.headers.cookie; //<<-- added this line
    res.render('index', { req, providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }] });
  });
```

**Comment by BruneXX** [comment]
Excellent, I've added the line ```req.cookies = req.headers.cookie;````and started working, they definitively should add that to the documentation.

**Comment by BruneXX** [comment]
After this change someone experienced an issue with page render, I can't see my html code in the source code of the page...

**Comment by kuncevic** [comment]
@BruneXX are you running `npm run prerender` or `npm run serve:ssr` ?

**Comment by kuncevic** [comment]
@BruneXX are you running `npm run prerender` or `npm run serve:ssr` ? If you just `npm start` you wont see that viewing the page source`

**Comment by BruneXX** [comment]
Hi @kuncevic I'm currently experiencing new issues with this in universal v9.1.1 I cannot get the cookie on server side, doesn't exist in authenticated routes for resolvers.. IDK what's happening now.

**Comment by puneetverma05** [comment]
Hy @BruneXX ,
can you elaborate on whats actually happened? did you resolved that issue?

**Comment by BruneXX** [comment]
Hi @puneetverma05 I’m not using this package anymore, since I’ve not found the Issue, I’ve moved to @gorniv/ngx-universal

**Comment by puneetverma05** [comment]
@BruneXX  actually I haven't updated to Angular 9 yet right now on 8  
```req.cookies = req.headers.cookie;```
not working just getting empty cookies server-side on the client it works fine and req.headers.cookie does have the values  :(

**Comment by puneetverma05** [comment]
> @BruneXX actually I want to move from this lib but I haven't updated to Angular 9 yet right now on 8
> `req.cookies = req.headers.cookie;`
> This solution not helping just getting empty cookies server-side ,on the client it works fine and req.headers.cookie does have the values :(

And I’m also using an interceptor for absolute url change for server api request does that may interfere?

**Comment by BruneXX** [comment]
@puneetverma05 yes, I think that’s the issue, but when I’ve used angular v8 cookies with this package works just fine.

**Comment by puneetverma05** [comment]
@BruneXX  ok will look into it, thanks for your time :)

**Comment by BruneXX** [comment]
> > @BruneXX actually I want to move from this lib but I haven't updated to Angular 9 yet right now on 8
> > `req.cookies = req.headers.cookie;`
> > This solution not helping just getting empty cookies server-side ,on the client it works fine and req.headers.cookie does have the values :(
> 
> And I’m also using an interceptor for absolute url change for server api request does that may interfere?

@puneetverma05 IDK really, I’m using interceptors too but API urls are used always (server/browser) with absoluth path.

**Comment by puneetverma05** [comment]
cookie get all empty but when I do set any cookie from the server, the client receives, only it just client -> server not working.. can you anyhow share sample code for ```server.ts``` ?

**Comment by BruneXX** [comment]
@puneetverma05 I had that issue too, how are you setting the cookie in the client? Are you using SSL in your site?

**Comment by puneetverma05** [comment]
@BruneXX  just normal ```put()``` function

**Comment by puneetverma05** [comment]
Hey just for the update @BruneXX I fixed that, actually this lib is BROKEN.. 
instead of ```req.cookies = req.headers.cookie;``` I have created a ```req['cookie'] = req.headers.cookie```

**Comment by BruneXX** [comment]
Hi @puneetverma05 yes, that is what I've said, this lib is the problem, check the answer of @rkajbaf above.
Also I think that should be updated in the docs, anyway in my case when I've updated to ng v9 that didn't work and I've moved to https://github.com/Gorniv/ngx-universal so I haven't tried this lib again. I'm glad you can manage to make it work in your project. Cheers!

**Comment by sbarbat** [comment]
Try to remove the apostrophe on the providers:
```
{
     provide: REQUEST, useValue: (req)
},
{
     provide: RESPONSE, useValue: (res)
}
```
And `import {REQUEST, RESPONSE} from "@nguniversal/express-engine/tokens";`

It is working for me on Angular 9.1.4 and nguniversal/express-engine 9.1.1

**Comment by puneetverma05** [comment]
@sbarbat  than we don't need to do this `req.cookies = req.headers.cookie;` || `req['cookie'] = req.headers.cookie;`  right?

**Comment by sbarbat** [comment]
I don't think so. 

Version ngx-cookie@4.1.2 it's working like a charm in my implementation using Angular 9.1.4 and nguniversal/express-engine 9.1.1.

**Comment by salemdar** [comment]
Hopefully fixed. I created a `backend-test-app` to test this.
