### ISSUE TITLE
Angular 9 support

### ISSUE THREAD

**Issue by tgangso** [salemdar/ngx-cookie#106]
After upgrading to Angular v9, I get this issue when running ng-serve:

ERROR in The target entry-point "ngx-cookie" has missing dependencies:
 - @nguniversal/express-engine/tokens

**Comment by bkimminich** [comment]
If you declare yourself a dependency (or pin an existing one) to `v9.0.0-rc.2` of `express-engine` things worked again for me even with Angular 9. This is obviously more of a workaround.

See also https://github.com/bkimminich/juice-shop/issues/1313.

**Comment by adhed** [comment]
Do you have some other ideas for a solution for this problem?

**Comment by ilikeprograms** [comment]
Is this likely to be looked into soon?
Were going to be updating to Angular 9 and would like to continue the library.

**Comment by kochetkovSergeY** [comment]
We migrate to https://www.npmjs.com/package/ngx-cookie-service

**Comment by salemdar** [comment]
Fixed.
