### ISSUE TITLE
ngx-cookie support for Angular Universal

### ISSUE THREAD

**Issue by adebree** [salemdar/ngx-cookie#11]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[X] feature request
```

**Current behavior**

Current implementation of the CookieBackendService doesn't work with the current angular universal. The request / response aren't available in the current Zone as is currently the way to use it in the CookieBackendService implementation.

**Expected/desired behavior**

There is a fork of ngx-cookie which looks to address this issue:

https://github.com/jzahka/ngx-cookie/commit/d5bc30cc585093834c2ecdc984daf5c4ca70a602

So for the looks it would probably be fixed by getting that commit into ngx-cookie.

I tried to use that fork in my project, but didn't figure out how to do a post install build that works. The published ngx-cookie is compiled / build differently than what I can seem to be triggering. 

**Please tell us about your environment:**

* **ngx-cookie version:** 1.0.0

* **Angular version:** 4.1.3
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by dmitrysteblyuk** [comment]
I was wondering what type would request, response get? I'm using express on server-side and "headers" property is not defined there on type Response (there's only a method res.cookie(name, value[, options]))

**Comment by salemdar** [comment]
Should be fixed with the new version
