### ISSUE TITLE
Angular 9 support

### ISSUE THREAD

**Issue by naveendanda** [salemdar/ngx-cookie#110]
https://github.com/salemdar/ngx-cookie/blob/7c97205c4be1eeb8f23f663675c240d22f9b5a74/lib/src/lib/cookie.module.ts#L28

Need to update as per angular 9 as we are getting error as 'CookieModule.forRoot returns a ModuleWithProviders type without a generic type argument. Please add a generic type argument to the ModuleWithProviders type. If this occurrence is in library code you don't control, please contact the library authors.'

**Comment by salemdar** [comment]
Fixed.
