### ISSUE TITLE
ModuleWithProviders usage without type parameter no longer supported in angular 10.

### ISSUE THREAD

**Issue by FrancisS** [salemdar/ngx-cookie#112]
https://github.com/salemdar/ngx-cookie/blob/7c97205c4be1eeb8f23f663675c240d22f9b5a74/lib/src/lib/cookie.module.ts#L15

Support for using the ModuleWithProviders without a generic parameter has been removed as of angular 10. ngx-moment no longer compiles with angular 10.

ERROR in node_modules/ngx-cookie/lib/cookie.module.d.ts:7:46 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

7     static forRoot(options?: CookieOptions): ModuleWithProviders;

**Comment by salemdar** [comment]
Fixed
