### ISSUE TITLE
Can not set Cookie domain or options

### ISSUE THREAD

**Issue by Floyd1256** [salemdar/ngx-cookie#13]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
Typically, the domain along with other options are optional to set when setting a new cookie. Tried different formats for the domain, as I am currently testing on a local server, and none is showing up in the developer console in chrome. The only time the cookie is present is when I do not give it options

**Expected/desired behavior**
I am not sure if there is something wrong with the options I am setting, but I don't think so.

**Please tell us about your environment:**

* **ngx-cookie version:** 1.0.0

* **Angular version:** 4.1.2
* ** Ionic version:** 3.4.0

* **Browser:** [ Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by geetee24** [comment]
How did you set your options?  Provide code ?

**Comment by Floyd1256** [comment]
this._cookieService.put('TestCookie',"TestValue",{domain: '192.168.1.103'});

**Comment by bharath-srinivas** [comment]
It seems the cookie options are delimited by `;` instead of `,`.

**Comment by bharath-srinivas** [comment]
When I do ```this.cookieService.put(key, value, { path: '/', secure: true });``` I'm getting this string ```"my_cookie=somecookie;path=/;secure"``` which is why its not getting set. Notice that `secure` is not getting set as `secure=true`.

**Comment by pranav93** [comment]
Maybe there's a problem at https://github.com/salemdar/ngx-cookie/blob/master/src/cookie.service.ts#L181 ??

**Comment by celsomtrindade** [comment]
Same problem here (tested on Chrome and Firefox). When setting a cookieOption, the cookie doesn't add to the application. This is how I'm setting:

    const options: CookieOptions = {
        path: '/',
        domain: environment.mainUrl,
        secure: environment.production,
        expires: new Date(new Date().setFullYear(new Date().getFullYear() + 1))
    };

    this._cookie.put('my-token', JSON.stringify(token), options);

By removing the `options` from the `put()` method, everything works fine, but the cookie is set to "session" only.

**Comment by Floyd1256** [comment]
Alright I see, worth a shot. I have tried many formats but I guess since I am developing locally and I actually do not have a site name, it is causing issues concerning the domain. I will try to test and see if that solves it. Thanks!

**Comment by rafaelestevaofoster** [comment]
HI, i have a problem safari on IOS 10.3.3

i using this.cookieService.set('Test', 'Test created token'), but only IOS 10.3.3 does not work.

Exists work around?

**Comment by JaysQubeXon** [comment]
I'm having an issue with setting domain on the cookie.

@Floyd1256  have you managed to get a real site name to work?

**Comment by BruneXX** [comment]
Why this is closed now? I'm experiencing the same problem, is there a workaround for this? Thanks

**Comment by anwarulislam** [comment]
I'm experiencing the same problem here. can not set cookies when adding options

**Comment by iKonstX** [comment]
So this library does not support httpOnly cookies then? Lol

**Comment by iKonstX** [comment]
If you are getting this issue, make sure you are putting options that can be accessed by javascript.
Setting the cookie to httpOnly prevents javascript from accessing it, so setting it to true is not possible.
