### ISSUE TITLE
CookieBackendWriterService returns undefined when reading cookie value.

### ISSUE THREAD

**Issue by SuperheroicCoding** [salemdar/ngx-cookie#140]
Hi, 

https://github.com/salemdar/ngx-cookie/blob/bb6e938bc276bda042bea2a943c60683a237a220/projects/ngx-cookie-backend/src/lib/cookie-backend-writer.service.ts#L14

This tests displays the issue:

```js
cookieService.put('test', 'Super cookie');
console.log(cookieService.get('test')); // logs: undefined
console.log(request.headers.cookie); // logs: undefined
console.log(request.cookies); // logs: 'test=Super%20cookie;path=...'
```

I would suggest to use `request.cookies` as fallback for `request.headers.cookie`

Kind regards!

**Comment by SuperheroicCoding** [comment]
Further investigating I see that the `request.headers.cookie` are containing the original cookies that where present when making the request.

So maybe it would be better to merge the two fields.

**Comment by SuperheroicCoding** [comment]
Digging more, it seems that the request.cookie value is overwritten each time you set a cookies.
So this would also not be a solution for our use case. (Logik depends on the value written before into cookie.)

I found a workaround where `response.header('Set-Cookie')` merged with the request.headers.cookie could be used.

**Comment by salemdar** [comment]
Hey @SuperheroicCoding 

Thanks for spotting the issue. The thing is `request.headers.cookie` and `request.cookies` have different types. So to use latter as a fallback, we would need to convert it to string.

Your last solution makes more sense to me. Would you like to create a PR for that?

**Comment by SuperheroicCoding** [comment]
Create PR: https://github.com/salemdar/ngx-cookie/pull/144

**Comment by SuperheroicCoding** [comment]
#144

**Comment by mohamedaarab1994** [comment]
Would be nice if this PR gets merged soon, I'm facing the same issue and also a deadline for this project that depends on this package

**Comment by salemdar** [comment]
It should be fixed now.

**Comment by SuperheroicCoding** [comment]
@salemdar thank you very much!
