### ISSUE TITLE
Settings passed with forRoot are not being preserved with angular-cli build

### ISSUE THREAD

**Issue by yadue** [salemdar/ngx-cookie#15]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
When using angular-cli --prod option settings passed to CookieModule.forRoot are omitted.

**Expected/desired behavior**
When using angular-cli --prod option settings passed to CookieModule.forRoot are there.

**Reproduction of the problem**
Create a module, import CookieModule and set expires
CookieModule.forRoot({
            expires: new Date(24 * 60 * 60 * 1000 + Date.now())
        }),

**What is the expected behavior?**
It should keep settings

**Please tell us about your environment:**

* **ngx-cookie version:** 1.0.0

* **Angular version:** 4.2.2
 
* **Browser:** [all]

**Comment by el-davo** [comment]
Just came across the same issue. I am trying to use environment.ts file which has a string template like so

```
export const environment = {
  websocketUrl: `ws://${window.location.host}/websocket`
};
```

However when I try to use thise in the @NgModule it seems to come out as null

```
@NgModule({
  imports: [
    NavbarModule.forRoot({newsWebsocketUrl: environment.websocketUrl})
  ],
  declarations: [AppComponent],
  bootstrap: [AppComponent]
})
```

Strange thing is it will work if the string template is update to just be a string, like so

```
export const environment = {
  websocketUrl: 'ws://localhost:9000/websocket'
};
```

**Comment by andreaswarnaar** [comment]
Did you found any workaround or is there a solution?

**Comment by pos1tron** [comment]
I might be far off as I haven't spent a ton of time understanding how AOT works under the hood, but it seems to me that it doesn't like data types that can't be easily, statically analyzed.

Here's what I was trying to do that wasn't working:
```
CookieModule.forRoot({
  expires: moment().add(config.COOKIE_DAYS_ALIVE, 'days').toDate()
}),
```

However, I did a little test and got this working. If I use a string value for expires, it works:

```
CookieModule.forRoot({
  expires: 'Fri, 31 Dec 9999 23:59:59 GMT'
}),
```

Not sure how i'll solve my original case, but thought this much could help.

**Comment by pos1tron** [comment]
Here's something I just got working:
```
import { NgModule, ModuleWithProviders } from '@angular/core';
import { CookieModule, CookieService, COOKIE_OPTIONS, cookieServiceFactory, CookieOptionsProvider } from 'ngx-cookie';

export function cookieOptionsFactory() {
  return {
    domain: (<any>window).__env.COOKIE_DOMAIN,
    secure: (<any>window).__env.COOKIE_SECURE,
    expires: moment().add((<any>window).__env.COOKIE_DAYS_ALIVE, 'days').toDate()
  };
}

export const MyCookieModule: ModuleWithProviders = {
  ngModule: CookieModule,
  providers: [
    { provide: COOKIE_OPTIONS, useFactory: cookieOptionsFactory },
    { provide: CookieService, useFactory: cookieServiceFactory, deps: [CookieOptionsProvider]}
  ]
};

@NgModule({
  imports: [
    MyCookieModule
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

The key is to `useFactory` instead of `useValue` when providing `COOKIE_OPTIONS`.

**Comment by BruneXX** [comment]
Hi Guys, I've tried both @pos1tron soutions  none worked, there's an alternative to this?
