### ISSUE TITLE
Cookies as token containers

### ISSUE THREAD

**Issue by Tommolo** [salemdar/ngx-cookie#16]
Hi there.

I'm wondering if there is a guide that explain how to use the Cookie as storage of access/refresh token in angular2.

It seems that everyone admit the benefits fo Cookies in auth protocol via angular, but i can't find reference, and i've problems refreshing the token inside the cookie!

**Comment by salemdar** [comment]
I think this question is out of scope of this library. This library is only a simple between your app and cookies. It is up to you what to do with those cookies. You can google "auth / login angular" and check some examples.
