### ISSUE TITLE
Can not get cookie value when navigate to the path that the cookie options set

### ISSUE THREAD

**Issue by clcaza** [salemdar/ngx-cookie#17]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
I set the cookie in specified path throuth CookieOptions:
```
  const options = {path:'/login'}
  this.cookieService.put("account", account,options);
```
When i navigate to the path through router,i can not get the value. 

`router.navigateByUrl("/login");`

But if i request the url directly in browser, i can get the cookie value.

**Expected/desired behavior**

navigating to the path through router can get the cookie value. 

**Reproduction of the problem**
I guess when using router  to navigate, angular does not send a http request, for browser, the request url still is the old one, so can not get the cookie value.

**Please tell us about your environment:**

* **ngx-cookie version:** 1.0.0

* **Angular version:** 4.0.0
 
* **Browser:** Chrome 58 | Firefox 54 | IE 11 ]

**Comment by phoude** [comment]
I am having the same issue. I have found out that if I navigate to the page via router than my cookie is not available but if I enter the same url in my browser then the cookie is available. If I don't specify a path then browser set the path for me (!!).
