### ISSUE TITLE
Can't read cookie from Secure or Http checked cookie.

### ISSUE THREAD

**Issue by wbgreely** [salemdar/ngx-cookie#18]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ X ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

I'm trying to parse a cookie using the .get method.  Everything works perfectly in local with unsecured cookies.  However, when I deploy to dev on a secure URL, the .get returns undefined for the cookie value.  

**Please tell us about your environment:**

* **ngx-cookie version:** Current
* **Angular version:** 4.0.0
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by nerellamahesh** [comment]
@wbgreely I am also facing the same issue . In my local everything is working fine. But i if deploy to dev it is not working. I see that .set is also not working in dev environment. So i started using document.cookie .

Were you able to find out anything ?

**Comment by celsomtrindade** [comment]
Can you providenciar the code you are using to set the cookies? Are you sure you are not setting the option `secure: true`?

**Comment by bujashaka** [comment]
I have similar kind of issue. I can set secure/httponly cookie and i can see it in new request but can't access it. $request->cookies->all(); returns null. Site has ssl and https is on.

**Comment by RenaldasK** [comment]
You are not supposed to be able to read Secure or HTTPOnly cookies on the front-end in JavaScript, these can only be accessed on the serve, hence the reason they are called "Secure". Read here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Secure_and_HttpOnly_cookies
