### ISSUE TITLE
IE crashes due to introduction of template string

### ISSUE THREAD

**Issue by KiranShakya** [salemdar/ngx-cookie#182]
**Describe the bug**
At the utils line number 111 for v5.0.0, we have a template string which is not supported by IE.

**To Reproduce**
1. Just open in Internet Explorer, it crashes.

**Expected behavior**
The template string should either be transpiled properly with tsconfig target set as es5 or replaced with backward compatible regular string.

**Environment:**
 - Angular version: 8.x.x
 - Internet Explorer 11
 - Version 5.0.0

**Comment by cassianomon** [comment]
Happening to me too.
Angular version: 7.x.x
ngx-cookie: 5.0.0

**Comment by cassianomon** [comment]
Installed classlist.js as polyfills and still crashing in the definition of class CookieOptionsProvider

**Comment by cassianomon** [comment]
Any ideas for solving this @salemdar ?

**Comment by navjotschahal** [comment]
Any solution to this issue, unable to open angular apps after this dependency added to app on IE 11.
Also tried to use older version but they also are not getting imported.

**Comment by salemdar** [comment]
It should be fixed now.
