### ISSUE TITLE
Not compatible with common.js module syntax

### ISSUE THREAD

**Issue by harshes53** [salemdar/ngx-cookie#19]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
The package support ES6 module syntax which works perfectly fine when compiled using typescript loader, although when the package is used with Server-side Rendering Javascript Apps in which usually packages from `node_modules` are not compiled/transpiled, when running the app in Node.js runtime env, package is not compatible to use with `common.js` module syntax.

**Expected/desired behavior**
It should also be compatible with `common.js` module syntax.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar.

**What is the expected behavior?**
It should also be compatible with `common.js` module syntax.

**What is the motivation / use case for changing the behavior?**
To avoid transpiling the package when used with SSR apps running in Node env.

**Please tell us about your environment:**

* **ngx-cookie version:** 1.0.0

* **Angular version:** 4.3.x
 
* **Node.js:** [6.11.x]

**Comment by abdekalder** [comment]
Nothing about this issue? What is alternative of ngx-cookie for angular universal?

**Comment by harshes53** [comment]
@abdekalder you may try [ngx-cookie-service](https://www.npmjs.com/package/ngx-cookie-service)
