### ISSUE TITLE
Feature Request: Set SameSite attribute

### ISSUE THREAD

**Issue by rocketkittens** [salemdar/ngx-cookie#21]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```
Please add support to set SameSite attribute:
https://www.owasp.org/index.php/SameSite

**Comment by rongdilin** [comment]
+1

**Comment by shyamal890** [comment]
+1

**Comment by rsarmiento-pl** [comment]
+1

Please add this feature, 

Chrome [upgrade](https://blog.chromium.org/2020/02/samesite-cookie-changes-in-february.html) that will break some site that uses cookies.

**Comment by niravpatel9898** [comment]
+1
