### ISSUE TITLE
Replace deprecated OpaqueTokens with InjectionTokens<T>

### ISSUE THREAD

**Issue by noemi-salaun** [salemdar/ngx-cookie#22]
**I'm submitting a ...**
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
ngx-cookie use [OpaqueToken](https://angular.io/api/core/OpaqueToken) which are deprecated since Angular v4.0.0.

**Expected/desired behavior**
Use [InjectionToken](https://angular.io/api/core/InjectionToken) instead which are the generically typed replacement.

**What is the motivation / use case for changing the behavior?**
Angular v5 will remove some of the deprecate from v4, containing OpaqueToken.
See [Changelog 5.0.0-beta.6](https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes)

**Please tell us about your environment:**

* **ngx-cookie version:** 1.0.0

**Comment by SlimDogs** [comment]
👍 +1

**Comment by billdwhite** [comment]
Created a pull request that should fix this [here](https://github.com/salemdar/ngx-cookie/pull/31)
