### ISSUE TITLE
Cannot install this package in angular 4.3.6

### ISSUE THREAD

**Issue by teddywest32** [salemdar/ngx-cookie#23]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
Cannot install this package in angular 4.3.6

**Expected/desired behavior**
Should be able to install the package.

**Reproduction of the problem**
`$ npm install ngx-cookie --save
C:\xampp\htdocs\angular4
+-- UNMET PEER DEPENDENCY @angular/common@4.3.6
+-- UNMET PEER DEPENDENCY @angular/core@4.3.6
 -- ngx-cookie@1.0.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\angular4\node_modules\es5-ext\package.json'
npm WARN angular2-cookie@1.2.6 requires a peer of @angular/common@^2.0.0 but none was installed.
npm WARN angular2-cookie@1.2.6 requires a peer of @angular/core@^2.0.0 but none was installed.
`

**What is the expected behavior?**
Able to install the package

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 8.1 

* **ngx-cookie version:** 1.2.6

* **Angular version:** 4.3.6
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

**Comment by arvindsanwaldev** [comment]
I am also getting same issue.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.10.0-35-generic
npm ERR! argv "/home/username/.nvm/versions/node/v6.9.1/bin/node" "/home/username/.nvm/versions/node/v6.9.1/bin/npm" "install" "ngx-cookie@1.0.0" "--save"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path /node_modules/flot
npm ERR! code EISGIT

npm ERR! git /node_modules/flot: Appears to be a git repo or submodule.
npm ERR! git     /node_modules/flot
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log

**Comment by salemdar** [comment]
Just remove `angular2-cookie` from your dependencies, remove `node_modules` and perform a clean install. It should be ok.
