### ISSUE TITLE
ngx-cookie-backend version 5.0.1 has a peer dependency to ngx-cookie: 5.0.0.

### ISSUE THREAD

**Issue by horinf** [salemdar/ngx-cookie#275]
**Describe the bug**
ngx-cookie-backend version 5.0.1 has a peer dependency - "ngx-cookie": "5.0.0".
So, I just can't use ngx-cookie of version 5.0.1 - I need 5.0.0 for ngx-cookie-backend

**To Reproduce**
Just try to run "npm install" command for project with following dependencies in package.json file
    "ngx-cookie": "5.0.1",
    "ngx-cookie-backend": "5.0.1",

**Expected behavior**
Dependencies installed, project ready to build

**Stacktrace**
(node:20628) ExperimentalWarning: The fs.promises API is experimental
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: ngx-cookie@5.0.1
npm ERR! node_modules/ngx-cookie
npm ERR!   ngx-cookie@"^5.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer ngx-cookie@"5.0.0" from ngx-cookie-backend@5.0.1
npm ERR! node_modules/ngx-cookie-backend
npm ERR!   ngx-cookie-backend@"^5.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Environment:**
 - Angular version 11.2.1

**Additional context**

**Comment by salemdar** [comment]
@horinf thanks for spotting the issue. Should be fixed with v5.0.2. Please update.
