### ISSUE TITLE
Getting NullInjectorError,StaticInjectorError if application is rediected to new tab

### ISSUE THREAD

**Issue by ryan1509** [salemdar/ngx-cookie#284]
`main-es2015.31938ab66d5d945adfdb.js:1 ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(r)[class{constructor(n,l){this.document=n,this.platformId=l,this.documentIsAccessible=Object(i.isPlatformBrowser)(this.platformId)}check(n){return!!this.documentIsAccessible&&(n=encodeURIComponent(n),this.getCookieRegExp(n).test(this.document.cookie))}get(n){if(this.documentIsAccessible&&this.check(n)){n=encodeURIComponent(n);const l=this.getCookieRegExp(n).exec(this.document.cookie);return decodeURIComponent(l[1])}return""}getAll(){if(!this.documentIsAccessible)return{};const n={},l=this.document;if(l.cookie&&""!==l.cookie){const t=l.cookie.split(";");for(let l=0;l<t.length;l+=1){const e=t[l].split("=");e[0]=e[0].replace(/^ /,""),n[decodeURIComponent(e[0])]=decodeURIComponent(e[1])}}return n}set(n,l,t,e,a,o,i){if(!this.documentIsAccessible)return;let u=encodeURIComponent(n)+"="+encodeURIComponent(l)+";";t&&(u+="number"==typeof t?"expires="+new Date((new Date).getTime()+1e3*t*60*60*24).toUTCString()+";":"expires="+t.toUTCString()+";"),e&&(u+="path="+e+";"),a&&(u+="domain="+a+";"),o&&(u+="secure;"),i&&(u+="sameSite="+i+";"),this.document.cookie=u}delete(n,l,t){this.documentIsAccessible&&this.set(n,"",new Date("Thu, 01 Jan 1970 00:00:01 GMT"),l,t)}deleteAll(n,l){if(!this.documentIsAccessible)return;const t=this.getAll();for(const e in t)t.hasOwnProperty(e)&&this.delete(e,n,l)}getCookieRegExp(n){const l=n.replace(/([\[\]\{\}\(\)\|\=\;\+\?\,\.\*\^\$])/gi,"\\$1");return new RegExp("(?:^"+l+"|;\\s*"+l+")=(.*?)(?:;|$)","g")}}]: 
  StaticInjectorError(Platform: core)[class{constructor(n,l){this.document=n,this.platformId=l,this.documentIsAccessible=Object(i.isPlatformBrowser)(this.platformId)}check(n){return!!this.documentIsAccessible&&(n=encodeURIComponent(n),this.getCookieRegExp(n).test(this.document.cookie))}get(n){if(this.documentIsAccessible&&this.check(n)){n=encodeURIComponent(n);const l=this.getCookieRegExp(n).exec(this.document.cookie);return decodeURIComponent(l[1])}return""}getAll(){if(!this.documentIsAccessible)return{};const n={},l=this.document;if(l.cookie&&""!==l.cookie){const t=l.cookie.split(";");for(let l=0;l<t.length;l+=1){const e=t[l].split("=");e[0]=e[0].replace(/^ /,""),n[decodeURIComponent(e[0])]=decodeURIComponent(e[1])}}return n}set(n,l,t,e,a,o,i){if(!this.documentIsAccessible)return;let u=encodeURIComponent(n)+"="+encodeURIComponent(l)+";";t&&(u+="number"==typeof t?"expires="+new Date((new Date).getTime()+1e3*t*60*60*24).toUTCString()+";":"expires="+t.toUTCString()+";"),e&&(u+="path="+e+";"),a&&(u+="domain="+a+";"),o&&(u+="secure;"),i&&(u+="sameSite="+i+";"),this.document.cookie=u}delete(n,l,t){this.documentIsAccessible&&this.set(n,"",new Date("Thu, 01 Jan 1970 00:00:01 GMT"),l,t)}deleteAll(n,l){if(!this.documentIsAccessible)return;const t=this.getAll();for(const e in t)t.hasOwnProperty(e)&&this.delete(e,n,l)}getCookieRegExp(n){const l=n.replace(/([\[\]\{\}\(\)\|\=\;\+\?\,\.\*\^\$])/gi,"\\$1");return new RegExp("(?:^"+l+"|;\\s*"+l+")=(.*?)(?:;|$)","g")}}]: 
    NullInjectorError: No provider for class{constructor(n,l){this.document=n,this.platformId=l,this.documentIsAccessible=Object(i.isPlatformBrowser)(this.platformId)}check(n){return!!this.documentIsAccessible&&(n=encodeURIComponent(n),this.getCookieRegExp(n).test(this.document.cookie))}get(n){if(this.documentIsAccessible&&this.check(n)){n=encodeURIComponent(n);const l=this.getCookieRegExp(n).exec(this.document.cookie);return decodeURIComponent(l[1])}return""}getAll(){if(!this.documentIsAccessible)return{};const n={},l=this.document;if(l.cookie&&""!==l.cookie){const t=l.cookie.split(";");for(let l=0;l<t.length;l+=1){const e=t[l].split("=");e[0]=e[0].replace(/^ /,""),n[decodeURIComponent(e[0])]=decodeURIComponent(e[1])}}return n}set(n,l,t,e,a,o,i){if(!this.documentIsAccessible)return;let u=encodeURIComponent(n)+"="+encodeURIComponent(l)+";";t&&(u+="number"==typeof t?"expires="+new Date((new Date).getTime()+1e3*t*60*60*24).toUTCString()+";":"expires="+t.toUTCString()+";"),e&&(u+="path="+e+";"),a&&(u+="domain="+a+";"),o&&(u+="secure;"),i&&(u+="sameSite="+i+";"),this.document.cookie=u}delete(n,l,t){this.documentIsAccessible&&this.set(n,"",new Date("Thu, 01 Jan 1970 00:00:01 GMT"),l,t)}deleteAll(n,l){if(!this.documentIsAccessible)return;const t=this.getAll();for(const e in t)t.hasOwnProperty(e)&&this.delete(e,n,l)}getCookieRegExp(n){const l=n.replace(/([\[\]\{\}\(\)\|\=\;\+\?\,\.\*\^\$])/gi,"\\$1");return new RegExp("(?:^"+l+"|;\\s*"+l+")=(.*?)(?:;|$)","g")}}!
NullInjectorError: StaticInjectorError(r)[class{constructor(n,l){this.document=n,this.platformId=l,this.documentIsAccessible=Object(i.isPlatformBrowser)(this.platformId)}check(n){return!!this.documentIsAccessible&&(n=encodeURIComponent(n),this.getCookieRegExp(n).test(this.document.cookie))}get(n){if(this.documentIsAccessible&&this.check(n)){n=encodeURIComponent(n);const l=this.getCookieRegExp(n).exec(this.document.cookie);return decodeURIComponent(l[1])}return""}getAll(){if(!this.documentIsAccessible)return{};const n={},l=this.document;if(l.cookie&&""!==l.cookie){const t=l.cookie.split(";");for(let l=0;l<t.length;l+=1){const e=t[l].split("=");e[0]=e[0].replace(/^ /,""),n[decodeURIComponent(e[0])]=decodeURIComponent(e[1])}}return n}set(n,l,t,e,a,o,i){if(!this.documentIsAccessible)return;let u=encodeURIComponent(n)+"="+encodeURIComponent(l)+";";t&&(u+="number"==typeof t?"expires="+new Date((new Date).getTime()+1e3*t*60*60*24).toUTCString()+";":"expires="+t.toUTCString()+";"),e&&(u+="path="+e+";"),a&&(u+="domain="+a+";"),o&&(u+="secure;"),i&&(u+="sameSite="+i+";"),this.document.cookie=u}delete(n,l,t){this.documentIsAccessible&&this.set(n,"",new Date("Thu, 01 Jan 1970 00:00:01 GMT"),l,t)}deleteAll(n,l){if(!this.documentIsAccessible)return;const t=this.getAll();for(const e in t)t.hasOwnProperty(e)&&this.delete(e,n,l)}getCookieRegExp(n){const l=n.replace(/([\[\]\{\}\(\)\|\=\;\+\?\,\.\*\^\$])/gi,"\\$1");return new RegExp("(?:^"+l+"|;\\s*"+l+")=(.*?)(?:;|$)","g")}}]: 
  StaticInjectorError(Platform: core)[class{constructor(n,l){this.document=n,this.platformId=l,this.documentIsAccessible=Object(i.isPlatformBrowser)(this.platformId)}check(n){return!!this.documentIsAccessible&&(n=encodeURIComponent(n),this.getCookieRegExp(n).test(this.document.cookie))}get(n){if(this.documentIsAccessible&&this.check(n)){n=encodeURIComponent(n);const l=this.getCookieRegExp(n).exec(this.document.cookie);return decodeURIComponent(l[1])}return""}getAll(){if(!this.documentIsAccessible)return{};const n={},l=this.document;if(l.cookie&&""!==l.cookie){const t=l.cookie.split(";");for(let l=0;l<t.length;l+=1){const e=t[l].split("=");e[0]=e[0].replace(/^ /,""),n[decodeURIComponent(e[0])]=decodeURIComponent(e[1])}}return n}set(n,l,t,e,a,o,i){if(!this.documentIsAccessible)return;let u=encodeURIComponent(n)+"="+encodeURIComponent(l)+";";t&&(u+="number"==typeof t?"expires="+new Date((new Date).getTime()+1e3*t*60*60*24).toUTCString()+";":"expires="+t.toUTCString()+";"),e&&(u+="path="+e+";"),a&&(u+="domain="+a+";"),o&&(u+="secure;"),i&&(u+="sameSite="+i+";"),this.document.cookie=u}delete(n,l,t){this.documentIsAccessible&&this.set(n,"",new Date("Thu, 01 Jan 1970 00:00:01 GMT"),l,t)}deleteAll(n,l){if(!this.documentIsAccessible)return;const t=this.getAll();for(const e in t)t.hasOwnProperty(e)&&this.delete(e,n,l)}getCookieRegExp(n){const l=n.replace(/([\[\]\{\}\(\)\|\=\;\+\?\,\.\*\^\$])/gi,"\\$1");return new RegExp("(?:^"+l+"|;\\s*"+l+")=(.*?)(?:;|$)","g")}}]: 
    NullInjectorError: No provider for class{constructor(n,l){this.document=n,this.platformId=l,this.documentIsAccessible=Object(i.isPlatformBrowser)(this.platformId)}check(n){return!!this.documentIsAccessible&&(n=encodeURIComponent(n),this.getCookieRegExp(n).test(this.document.cookie))}get(n){if(this.documentIsAccessible&&this.check(n)){n=encodeURIComponent(n);const l=this.getCookieRegExp(n).exec(this.document.cookie);return decodeURIComponent(l[1])}return""}getAll(){if(!this.documentIsAccessible)return{};const n={},l=this.document;if(l.cookie&&""!==l.cookie){const t=l.cookie.split(";");for(let l=0;l<t.length;l+=1){const e=t[l].split("=");e[0]=e[0].replace(/^ /,""),n[decodeURIComponent(e[0])]=decodeURIComponent(e[1])}}return n}set(n,l,t,e,a,o,i){if(!this.documentIsAccessible)return;let u=encodeURIComponent(n)+"="+encodeURIComponent(l)+";";t&&(u+="number"==typeof t?"expires="+new Date((new Date).getTime()+1e3*t*60*60*24).toUTCString()+";":"expires="+t.toUTCString()+";"),e&&(u+="path="+e+";"),a&&(u+="domain="+a+";"),o&&(u+="secure;"),i&&(u+="sameSite="+i+";"),this.document.cookie=u}delete(n,l,t){this.documentIsAccessible&&this.set(n,"",new Date("Thu, 01 Jan 1970 00:00:01 GMT"),l,t)}deleteAll(n,l){if(!this.documentIsAccessible)return;const t=this.getAll();for(const e in t)t.hasOwnProperty(e)&&this.delete(e,n,l)}getCookieRegExp(n){const l=n.replace(/([\[\]\{\}\(\)\|\=\;\+\?\,\.\*\^\$])/gi,"\\$1");return new RegExp("(?:^"+l+"|;\\s*"+l+")=(.*?)(?:;|$)","g")}}!
    at re.get (main-es2015.31938ab66d5d945adfdb.js:1)
    at main-es2015.31938ab66d5d945adfdb.js:1
    at e (main-es2015.31938ab66d5d945adfdb.js:1)
    at it.get (main-es2015.31938ab66d5d945adfdb.js:1)
    at main-es2015.31938ab66d5d945adfdb.js:1
    at e (main-es2015.31938ab66d5d945adfdb.js:1)
    at it.get (main-es2015.31938ab66d5d945adfdb.js:1)
    at eg (main-es2015.31938ab66d5d945adfdb.js:1)
    at Og.get (main-es2015.31938ab66d5d945adfdb.js:1)
    at ee (main-es2015.31938ab66d5d945adfdb.js:1)
    at P (polyfills-es2015.0d6bdc0dfb217e674971.js:1)
    at P (polyfills-es2015.0d6bdc0dfb217e674971.js:1)
    at polyfills-es2015.0d6bdc0dfb217e674971.js:1
    at a.invokeTask (polyfills-es2015.0d6bdc0dfb217e674971.js:1)
    at Object.onInvokeTask (main-es2015.31938ab66d5d945adfdb.js:1)
    at a.invokeTask (polyfills-es2015.0d6bdc0dfb217e674971.js:1)
    at t.runTask (polyfills-es2015.0d6bdc0dfb217e674971.js:1)
    at _ (polyfills-es2015.0d6bdc0dfb217e674971.js:1)`

**Comment by salemdar** [comment]
@ryan1509 can you please describe the issue, steps to produce, environment info etc. 
Until then I close the issue.
