### ISSUE TITLE
Option to not encode cookie values

### ISSUE THREAD

**Issue by entrodus** [salemdar/ngx-cookie#29]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```

**Current behavior**
Cookie value gets encoded when persisted.

**Expected/desired behavior**
Provide an option to not encode cookie value when persisting. 

**Reproduction of the problem**
Try to store a cookie value of 'foo=bar' and it will be stored as 'Foo%3Dbar'

**What is the motivation / use case for changing the behavior?**
It is not possible to share the same cookie with legacy applications that do not encode cookie values 

* **ngx-cookie version:** 1.0.0

* **Angular version:** 4.3.5
 
* **Browser:** all

**Comment by entrodus** [comment]
#30 I have created a pull request that implements this feature. I would be happy to make any requested changes.

**Comment by salemdar** [comment]
Merged the PR
