### ISSUE TITLE
Breaking change 1.0.0 => 1.0.1

### ISSUE THREAD

**Issue by rgamage** [salemdar/ngx-cookie#34]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

When building with @angular/core 2.4.5, running the webpack bundle command shows this error:
WARNING in ./~/ngx-cookie/src/cookie-options-provider.js
4:32-46 "export 'InjectionToken' was not found in '@angular/core'

ERROR in [at-loader] ./node_modules/ngx-cookie/src/cookie-options-provider.d.ts:1:10 
    TS2305: Module '"F:/A3/_w/40/s/OnlineOrdering/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.

**Expected/desired behavior**
Desired behavior is to publish with no errors.  This works with version 1.0.0, but breaks with version 1.0.1, which was unexpected.

**Reproduction of the problem**
create a new template using the command "dotnet new angular" and set the package.json the same as I show below.  Try to build using the webpack bundle command.  You will see the error message.

>node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js

**What is the expected behavior?**
Should build with no errors

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Our project was based on the ASP.NET template project, created with the command "dotnet new angular", which builds a SPA application using ASP.NET backend and Angular/typescript front end, with webpack as the bundler.

* **ngx-cookie version:** 1.0.0 -> 1.0.1

* **Angular version:** 2.4.5
 
* **Browser:** [all ]

My package.json file:

`  "dependencies": {
    "@angular/common": "^2.4.5",
    "@angular/compiler": "^2.4.5",
    "@angular/core": "^2.4.5",
    "@angular/forms": "^2.4.5",
    "@angular/http": "^2.4.5",
    "@angular/platform-browser": "^2.4.5",
    "@angular/platform-browser-dynamic": "^2.4.5",
    "@angular/platform-server": "^2.4.5",
    "@angular/router": "^3.4.5",
    "@ng-idle/core": "^2.0.0-beta.12",
    "@ng-idle/keepalive": "^2.0.0-beta.12",
    "@types/node": "^6.0.42",
    "angular2-cool-http": "~2.1.0",
    "angular2-jwt": "^0.2.3",
    "angular2-platform-node": "~2.0.11",
    "angular2-template-loader": "^0.6.2",
    "angular2-universal": "^2.1.0-rc.1",
    "angular2-universal-patch": "^0.2.1",
    "angular2-universal-polyfills": "^2.1.0-rc.1",
    "aspnet-prerendering": "^2.0.0",
    "aspnet-webpack": "^1.0.17",
    "awesome-typescript-loader": "^3.0.0",
    "bootstrap": "^3.3.7",
    "css": "^2.2.1",
    "css-loader": "^0.25.0",
    "es6-shim": "^0.35.1",
    "event-source-polyfill": "^0.0.7",
    "expose-loader": "^0.7.1",
    "extract-text-webpack-plugin": "^2.0.0-rc",
    "file-loader": "^0.9.0",
    "font-awesome": "4.7.0",
    "html-loader": "^0.4.4",
    "isomorphic-fetch": "^2.2.1",
    "jquery": "^2.2.1",
    "json-loader": "^0.5.4",
    "ng2-toastr": "1.3.3",
    "ngx-cookie": "^1.0.0",
    "ngx-mydatepicker": "2.0.12",
    "preboot": "^4.5.2",
    "raw-loader": "^0.5.1",
    "rxjs": "^5.0.1",
    "style-loader": "^0.13.1",
    "to-string-loader": "^1.1.5",
    "typescript": "^2.2.1",
    "url-loader": "^0.5.7",
    "webpack": "^2.2.0",
    "webpack-hot-middleware": "^2.12.2",
    "webpack-merge": "^0.14.1",
    "zone.js": "^0.7.6"
  },
  "devDependencies": {
    "@types/chai": "^3.4.34",
    "@types/jasmine": "^2.5.37",
    "chai": "^3.5.0",
    "jasmine": "^2.6.0",
    "jasmine-core": "^2.5.2",
    "karma": "^1.7.0",
    "karma-chai": "^0.1.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-webpack": "^1.8.0"
  }`

**Comment by hccampos** [comment]
InjectionToken was added in Angular 4 and replaces OpaqueToken, which got deprecated in Angular 4 as well and just got removed in Angular 5. Maybe ngx-cookie could publish to 2.0.0 instead of 1.0.0 since it is, indeed, a breaking change. However, upgrading to at least Angular 4 should be very straightforward since they (in theory) didn't add any breaking changes there.

**Comment by rgamage** [comment]
Thanks for the quick response.  Yes I'd recommend bumping the major version on this since I imagine it is a breaking change for many people.  Going to Angular 4.x may be simple in theory, but there is a domino effect with other libs in our project, and we don't have the time in our schedule to stop and re-factor for this.  Wish there were a better way to automate the continual update of these libs.  It seems like a very fragile eco-system that can break at any moment when you have so many dependencies and they are all changing daily.  Life on the bleeding edge!

**Comment by josephliccini** [comment]
+1 I'd recommend bumping major version.  Seeing the same thing in various other libraries (especially on InjectionToken / OpaqueToken rename)

**Comment by hccampos** [comment]
Even better would have been for Angular to not even change the thing in the
first place since there was not much gained there anyway and, as we can
see, quite a bit of pain to be had for people who can't be on the leading
edge all the time.

**Comment by salemdar** [comment]
I am sorry folks, it is my mistake, that should have been indeed a major version change. I will drop angular 2 from peerDependencies and bump the version to 2.0. But it is probably too late for 1.0.1 :(

**Comment by RicardoVaranda** [comment]
@salemdar Any chance of the deps being bumped to support Angular 5 also, getting a very verbose npm install due to it not being 'compatible'

**Comment by salemdar** [comment]
v2.0.1 now supports Angular 5.
