### ISSUE TITLE
bump angular dependency to ^5.0.0

### ISSUE THREAD

**Issue by JohanVersteeg** [salemdar/ngx-cookie#36]
I'm submitting a ...
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

Can you update the angular dependency to v5?

**Comment by rimlin** [comment]
+1, after upgrade to Angular 5 I caught the error:
ERROR in `.../node_modules/ngx-cookie/src/cookie-options-provider.d.ts (1,20): Module '.../node_modules/@angular/core/core"'` has no exported member 'OpaqueToken'.

**Comment by zenkkor** [comment]
+1 on this, this is the only package that is breaking the update for us.

**Comment by salemdar** [comment]
Fixed with the version 2.0.0.
