### ISSUE TITLE
Error thrown when application launched

### ISSUE THREAD

**Issue by jtsom** [salemdar/ngx-cookie#37]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
Starting a simple Angular 5 application throws an error in the Chrome dev console:

```
compiler.js:466 Uncaught Error: Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.
    at syntaxError (compiler.js:466)
    at eval (compiler.js:15088)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:15071)
    at JitCompiler._loadModules (compiler.js:33486)
    at JitCompiler._compileModuleAndComponents (compiler.js:33447)
    at JitCompiler.compileModuleAsync (compiler.js:33363)
    at CompilerImpl.compileModuleAsync (platform-browser-dynamic.js:230)
    at PlatformRef.bootstrapModule (core.js:5446)
    at eval (main.ts:10)
```
removing the line `CookieModule.forRoot()` in the `[imports]` of the app.module.ts file eliminated the exception.

**Expected/desired behavior**
Don't throw exception.

**Please tell us about your environment:**

* **ngx-cookie version:** 2.0.0

* **Angular version:** 
```Angular CLI: 1.5.0
Node: 8.8.1
OS: linux x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc0
@angular/cli: 1.5.0
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.0.0-rc0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1
```
 
* **Browser:** Chrome

**Comment by salemdar** [comment]
Could you show you code as well?

**Comment by jtsom** [comment]
```
  imports: [
    BrowserModule,
    FormsModule,
    HttpClientModule,
    BrowserAnimationsModule,
    CookieModule.forRoot(),
    AngularFireModule.initializeApp(environment.firebase),
    AngularFireDatabaseModule,
    AngularFireAuthModule,
    FlexLayoutModule,
    MatTableModule,
  ],
```

That's as far as I got...

**Comment by salemdar** [comment]
And this is your main `AppModule`, right?

**Comment by jtsom** [comment]
Yes.

```
import { CompetitionService } from './competition/competition.service';
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { AppComponent } from './app.component';
import { CompetitionListComponent } from './competition-list/competition-list.component';
import { CookieModule }  from 'ngx-cookie';
import { AngularFireModule } from 'angularfire2';
import { AngularFireDatabaseModule } from 'angularfire2/database';
import { AngularFireAuthModule } from 'angularfire2/auth';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { environment } from '../environments/environment';
import { MatchListComponent } from './match-list/match-list.component';
import { AuthService } from './shared/auth.service';
import { FlexLayoutModule  } from '@angular/flex-layout';
import { MatTableModule } from '@angular/material';

@NgModule({
  declarations: [
    AppComponent,
    CompetitionListComponent,
    MatchListComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpClientModule,
    BrowserAnimationsModule,
    // CookieModule.forRoot(),
    AngularFireModule.initializeApp(environment.firebase),
    AngularFireDatabaseModule,
    AngularFireAuthModule,
    FlexLayoutModule,
    MatTableModule,
  ],

  providers: [CompetitionService, AuthService],
  bootstrap: [AppComponent]
})
export class AppModule { }

```

**Comment by salemdar** [comment]
There's a problem with JiT which I will dig deeper later. For the moment you can use `--aot` flag:

```bash
ng serve --aot
ng build --aot
```

**Comment by jtsom** [comment]
Yep, that does seem to work around the problem.

(I'm running the CLI v. 1.5 and I had thought that by default AOT was on... Guess it doesn't seem to be)

**Comment by wis-ekubesh** [comment]
The problem happening because current compiled index.js file doesn't contain `decorate` part like this 

`CookieModule = CookieModule_1 = __decorate([
    NgModule({
        providers: [CookieOptionsProvider]
    })
], CookieModule);`

I think it's build problem but not sure how I can fix it.

Current solution - use umd module until fixes isn't ready.

`import { CookieModule } from 'ngx-cookie/bundles/ngx-cookie.umd.js';`

**Comment by jtsom** [comment]
Maybe open an issue on the Angular or Angular CLI repos?

**Comment by wis-ekubesh** [comment]
@jtsom not sure. I don't use Angular CLI and other modules in my project work fine. I have problem only with ngx-cookie and I found the problem. It just missed `decorate`. I've compared with previous releases and it worked before and `decorate` was included in bundled index.js

**Comment by namerci** [comment]
I have same problem, but I want to use it with SSR (Server Side Rendering).

`Unexpected value '[object Object]' imported by the module 'AppServerModule'. Please add a @NgModule annotation.`

I have two parent modules, `AppServerModule` and `AppBrowserModule`. Both imports `AppModule`. Where should I put `CookieModule.forRoot()`? Should I put `CookieModule.forChild()` in any module where I use `CookieService`?

**Comment by salemdar** [comment]
@wis-ekubesh Thanks for the detective work 👍 . I will find the solution and release fix.

**Comment by ltoshev** [comment]
I am experiencing same problem. Looking for fix?

**Comment by Sieabah** [comment]
Does anyone know if downgrading to ngx-cookie v1 solves the issue or if it's a problem with how Angular 5 is handling this module.

**Comment by salemdar** [comment]
**v2.0.1** has just released. The problem was **ngc** wasn't playing nice with **Typescript v2.6**. So I downgraded it to **v2.4.2**. 

I am closing the issue but feel free to reopen if you encounter the same problem again.
