### ISSUE TITLE
ngx-cookie-service library

### ISSUE THREAD

**Issue by stevermeister** [salemdar/ngx-cookie#393]
Hi, @salemdar! 

I'm a [ngx-cookie-service](https://github.com/stevermeister/ngx-cookie-service) library contributor.
It looks like our libraries are doing the same thing. 
I suggest combining the effort and putting it into one library. 
What do you think?

**Comment by kuncevic** [comment]
just migrated to [ngx-cookie-service](https://github.com/stevermeister/ngx-cookie-service), pretty much imports replace + `.put()` => `.set()`

**Comment by tavelli** [comment]
> just migrated to [ngx-cookie-service](https://github.com/stevermeister/ngx-cookie-service), pretty much imports replace + `.put()` => `.set()`

yea same here. also `.remove()` => `.delete()`, and path becomes second paramter in delete instead of `{path}` in ngx-cookie.
