### ISSUE TITLE
Expose COOKIE_OPTIONS and CookieOptionsProvider tokens

### ISSUE THREAD

**Issue by Necroskillz** [salemdar/ngx-cookie#4]
Hi,

Could you please release the changes made to https://github.com/salemdar/ngx-cookie/blob/master/index.ts?

I need `COOKIE_OPTIONS` to specify options with a factory, and I also extend `CookieService` and add some custom methods on top of it (that also use `CookieOptions`), in case you are wondering about use cases.

For now I use 
`import { COOKIE_OPTIONS, CookieOptionsProvider } from 'ngx-cookie/src/cookie-options-provider';`, but it would be nicer to just import these from `ngx-cookie`.

**Comment by LeeGar** [comment]
Is there a reason why CookieOptionsProvider isn't being exposed still?

**Comment by julienR2** [comment]
Good question, but it would be helpful indeed !
When you want to provide the service to a custom provider, you must provide `CookieOptionsProvider` in `new CookieService();`
