### ISSUE TITLE
SyntaxError: Unexpected token import when used on the server-side

### ISSUE THREAD

**Issue by laurentgoudet** [salemdar/ngx-cookie#40]
Currently `ngx-cookie` breaks when used on the server-side as explained in angular/angular-cli#7200. In short, when targeting the server platform with the Angular CLI only the app itself is compiled, as the libraries' UMD bundles would then be used when running it in NodeJS. However, when said library is published at separate ES modules instead of a flatten one (FESM), the deep imports would then resolved to the ES modules (and not the UMD bundle) on the server-side, causing Node to fail as it doesn't understand ES modules (v8.5 does with a special flag, but only with the .mjs file extension):

```
/foo/node_modules/ngx-cookie/src/cookie.service.js:1
(function (exports, require, module, __filename, __dirname) { import { Injectable } from '@angular/core';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.ngx-cookie/src/cookie.service (/foo/universal/dist/main.bundle.js:31147:18)
```

Flattening the ESM output fixes that, and is also a best practice as per the [Angular Package Format guidelines](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview) as it allows for faster builds, and makes sure that private imports aren't being used.

**Comment by salemdar** [comment]
Hey @laurentgoudet thanks for the issue and the PR. I will check it until tomorrow, but are there any breaking changes?

**Comment by laurentgoudet** [comment]
nope, not that I'm aware of. Builds tools would just consume the "rolled-up" ESM bundle (`bundles/ngx-cookie.js`) instead of the tree of ES modules (`index.js` & friends). Afaik the only thing that could break is deep imports of "private" files, e.g. `import { CookieOptions } from 'ngx-cookie/src/cookie-options.model';`, but no one should be doing that anyway (and should need to as all symbols are re-exported).

**Comment by JLanghauser** [comment]
I'm still having this problem - Angular 4.4 and ngx-cookie 1.0.1 with SSR. Looks like this PR never got merged - @salemdar - did you go a different direction with this issue? Thanks!

**Comment by mrusmanali** [comment]
any update on this issue

**Comment by JLanghauser** [comment]
I ended up just using babel-cli to convert the ngx-cookie js in node_modules into working es2015 JS and it worked. For anyone else who is stuck here, install babel-cli and the es2015 preset and then add a pre-compile step like this one into your package.json: 

"fix:cookie": "node node_modules/babel-cli/bin/babel.js node_modules/ngx-cookie/ --out-dir node_modules/ngx-cookie/ --presets es2015",

I just make sure to run **npm run fix:cookie** anytime I nuke my node_modules folder and then the ngx-cookie code compiles and serves properly server-side.

I hope this helps - this is not a unique or elegant solution and I certainly didn't come up with it (there are about a dozen examples of this same syntax error strewn about as many ng libraries and this was listed as a fix there). 

Good luck - I hope this is helpful. If it isn't enough let me know and I will find the original issue I'm pilfering this from. The frontpage of Babel basically walks you through it - https://babeljs.io/

**Comment by abdekalder** [comment]
Any other solution for this issue?

**Comment by lgoudriaan** [comment]
@salemdar Can you take a look at the PR and merge this? This error is making the lib unusable.

**Comment by ilDon** [comment]
I'm still running in this issue, has this been included in v. 3.0.1?
