### ISSUE TITLE
How to create a session cookie?

### ISSUE THREAD

**Issue by gtamas** [salemdar/ngx-cookie#46]
Hi all!

A simple question: how can I set a session / transient cookie?
I omit the "expires" cookie option, but  max-age  property of the cookie is still set. How do I create a cookie without expiration date? I want it to be deleted automatically when the session ends.

Thanks in advance!

**Comment by tchbell** [comment]
@gtamas 
you should be able to set the expires to '' and it should be set for just the session
```
 this.cookieService.put(cookieName, value, {
          expires: '',
          path: '/'
        });
      }
```
