### ISSUE TITLE
SSR cookieService.get returns undefined when value is available

### ISSUE THREAD

**Issue by nicholasconfer** [salemdar/ngx-cookie#465]
**Describe the bug**

`this._cookieService.get('name')` returns undefined on SSR even when a value is available if there are multiple cookies available on the domain.  

This is because of logic between ngx-cookie and ngx-cookie-backend

In the [cookie backend writer service, line 54](https://github.com/salemdar/ngx-cookie/blob/d071130a8fa082e3ae8370373e501f0d49584389/projects/ngx-cookie-backend/src/lib/cookie-backend-writer.service.ts#L54
) , the key value is trimmed, and then put back together with the cookie separator of  `;`

This gets rid of the natural `; `  space that is between cookies in req.headers.cookie

In the [parseCookieString function, line 68](https://github.com/salemdar/ngx-cookie/blob/d071130a8fa082e3ae8370373e501f0d49584389/projects/ngx-cookie/src/lib/utils.ts#L68) the cookie is then parsed by splitting with the natural space `; `.  This works on the browser side, but not on the server side render since the cookie key value was trimmed.

This also impacts other methods like cookieService.getAll(), which then returns the cookie as a single name value with the value as the rest of the cookie string since no breaking `; ` can be found.

**To Reproduce**
1. Domain with multiple cookies active
2. Test in SSR

**Expected behavior**

ngx-cookie-backend should return a cookie string with `; ` between cookies instead of `;`. The space is needed.

Alternatively, you could split cookies in parseCookieString by `;` instead of `; `, and then trim the value.

**Environment:**
 - Any

**Comment by pavankjadda** [comment]
@nicholasconfer I am one of the maintainer of [ngx-cookie-service](https://github.com/stevermeister/ngx-cookie-service#server-side-rendering=). We recently added support for SSR (Angular Universal). Please check it out.

**Comment by pavankjadda** [comment]
> @pavankjadda I actually used your package first and didn't realize at the time SSR support was in preview.  That's what led me to this library.  If I understand you correctly, the SSR support is now fully functional?

Yes. We merged changes yesterday and released it. Follow docs for instructions and let us know if you find any issues.

**Comment by salemdar** [comment]
Fixed with 6.0.1
