### ISSUE TITLE
Cookie not getting deleted by remove('cookie_name') and removeAll()

### ISSUE THREAD

**Issue by niluroy** [salemdar/ngx-cookie#52]
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request

**Current behavior**
Unable to delete cookie. To set cookie I am using:
    
    setCookie(cookie: string) {
        this.cookieService.put('userDetails', JSON.stringify(cookie), { domain: 'localhost' });
    }
    

**Expected/desired behavior**

    logout() {
        this.securityService.setLoginStatus(false);
        console.log('cookie details before: ' + JSON.stringify(this.cookie));
        this.socketService.logout(JSON.parse(this.cookie).id);
        this.cookieService.remove('userDetails', { domain: 'localhost' });
        console.log('cookie details after: ' + JSON.stringify(this.cookie));
     }
    
It is still showing the cookie in application tab. And after remove() also the cookie details is getting printed.

**Comment by morrisonbrett** [comment]
I'm seeing the same behavior. Not working.  Tried `.remove()` and `.removeAll()`.

**Comment by niluroy** [comment]
I am still seeing the same behavior.

**Comment by bjornharvold** [comment]
I can confirm that when I create a cookie with domain, I can also remove it when I pass the same domain.

**Comment by SaydChada** [comment]
I also can't get rid of any cookies set by other domain than the host.

**Comment by qubiack** [comment]
I also have this problem

**Comment by shyamal890** [comment]
This issue is still there

**Comment by cassianomon** [comment]
Still happening

**Comment by Gereon99** [comment]
Kind of weird that you find so little about this. I would've thought there were a lot more people, who have this problem
