### ISSUE TITLE
 found version 4,  expected 3

### ISSUE THREAD

**Issue by qiuxiaoguang** [salemdar/ngx-cookie#56]
I  npm install ngx-cookie --save, then npm run build, get this error:

Error: Metadata version mismatch for module
            /Users/qiu/Downloads/fenbi_project/fenbi-wap/node_modules/ngx-cookie/dist/ngx-cookie.d.ts, found version 4,
            expected 3
if I change the version from 4 to 3 in   ngx-cookie.metadata.json  ,can get the right result.

by the way , your last verion is 3.0.1

please fix this bug thanks

**Comment by iwoogy** [comment]
I have the same problem too.

I uninstalled the package and I install version 3.0.1 and I still get the same error.

Please help thx.

**Comment by iwoogy** [comment]
By reading other issues reported 
https://github.com/salemdar/ngx-cookie/issues/38

I found out that using angular 4, version 1.0.1 needs to be installed.

It's working now.
