### ISSUE TITLE
DIST is missing all CookieOptions  files.

### ISSUE THREAD

**Issue by geetee24** [salemdar/ngx-cookie#59]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```
can you please provide those files in the dist?

**Current behavior**

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-cookie version:** x.x.x

* **Angular version:** 2.x.x
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by alandroid** [comment]
Noobs don't fill out the bug report template, ask dumb questions.
