### ISSUE TITLE
Seeing index.ts not found in my linter

### ISSUE THREAD

**Issue by treeder** [salemdar/ngx-cookie#6]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

```
file: 'file:///..../ui/node_modules/ngx-cookie/tsconfig.json'
severity: 'Error'
message: 'File '/.../ui/node_modules/ngx-cookie/index.ts' not found.'
at: '1,1'
source: 'ts'
```

**Expected/desired behavior**

Not to see this error. I suppose index.ts doesn't exist as defined tsconfig.json

**Please tell us about your environment:**

* **ngx-cookie version:** 1.0.0

* **Angular version:** 4.0.3

**Comment by salemdar** [comment]
`index.ts` is right there and I couldn't reproduce the problem. An example might be helpful.
