### ISSUE TITLE
Error in setting and removing cookies when using angular universal

### ISSUE THREAD

**Issue by frostme** [salemdar/ngx-cookie#64]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
When using universal, I am receiving the following error

```
ERROR TypeError: Cannot set property 'cookie' of undefined
    at CookieBackendService.set [as cookieString] (/Users/melliotfrost/projects/pensar/pensar-microlearning/node_modules/ngx-cookie/bundles/ngx-cookie.umd.js:477:46)
    at /Users/melliotfrost/projects/pensar/pensar-microlearning/node_modules/ngx-cookie/bundles/ngx-cookie.umd.js:400:39
    at CookieBackendService.CookieService.remove (/Users/melliotfrost/projects/pensar/pensar-microlearning/node_modules/ngx-cookie/bundles/ngx-cookie.umd.js:328:37)
    at l.removeToken (/Users/melliotfrost/projects/pensar/pensar-microlearning/dist/server.js:1:1311643)
    at SafeSubscriber._error (/Users/melliotfrost/projects/pensar/pensar-microlearning/dist/server.js:1:1308071)
    at SafeSubscriber.__tryOrUnsub (/Users/melliotfrost/projects/pensar/pensar-microlearning/node_modules/rxjs/Subscriber.js:239:16)
    at SafeSubscriber.error (/Users/melliotfrost/projects/pensar/pensar-microlearning/node_modules/rxjs/Subscriber.js:198:26)
    at Subscriber._error (/Users/melliotfrost/projects/pensar/pensar-microlearning/node_modules/rxjs/Subscriber.js:129:26)
    at Subscriber.error (/Users/melliotfrost/projects/pensar/pensar-microlearning/node_modules/rxjs/Subscriber.js:103:18)
    at MapSubscriber.Subscriber._error (/Users/melliotfrost/projects/pensar/pensar-microlearning/node_modules/rxjs/Subscriber.js:129:26)
```

**Expected/desired behavior**
Should be able to remove and set token when using universal

**Reproduction of the problem**
Just follow the steps mentioned in the readme of this repository.

**What is the expected behavior?**
No error on setting and removing cookies.

**What is the motivation / use case for changing the behavior?**
To get this library working with Universal

**Please tell us about your environment:**

* **ngx-cookie version:** 4.0.2

* **Angular version:** 5.2.8
 
* **Browser:** Chrome

**Comment by paulelieskwirrel** [comment]
Quick-dirty-fix for me (with Express) : 
```
app.engine('html', (_, options, callback) => {
  global['window'] = win;
  global['document'] = win.document;
  // Setting res.headers
  options.res.headers = options.res.getHeaders();
  renderModuleFactory(AppServerModuleNgFactory, {
    document: template,
    url: options.req.url,
    extraProviders: [
      provideModuleMap(LAZY_MODULE_MAP),
      {
        provide: 'REQUEST',
        useValue: options.req
      },
      {
        provide: 'RESPONSE',
        useValue: options.res
      }
    ]
  }).then(html => {
    callback(null, html);
  });
});```

**Comment by mike-suggitt** [comment]
I'm having the same issue even when passing through the REQUEST and RESPONSE references.
Express server:
```
res.render('./dist/index', {
        req: req,
        res: res,
        providers: [
            {
                provide: 'REQUEST', useValue: (req)
            },
            {
                provide: 'RESPONSE', useValue: (res)
            }
        ]
    });
```

Then in angular:
```
console.log(this.request.headers);
        this.cookieService.removeAll();
```
The console.log correctly dumps all the headers out but cookieService still thinks they aren't there

**Comment by paulelieskwirrel** [comment]
@mike-suggitt Have you tried with my snippet ? Could you please provide the all code ?

**Comment by mike-suggitt** [comment]
@paulelieskwirrel I didn't know as i'm using the code lifted from angular docs

server.js

```
const app = require('./application');
require( 'zone.js/dist/zone-node');
const express = require('express');
const ngExpressEngine = require('@nguniversal/express-engine').ngExpressEngine;
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

const {
    AppServerModuleNgFactory,
    LAZY_MODULE_MAP
} = require(`./dist-server/main`);

const {
    provideModuleMap
} = require('@nguniversal/module-map-ngfactory-loader');

const provider = provideModuleMap(LAZY_MODULE_MAP);

app.engine(
    'html',
    ngExpressEngine({
        bootstrap: AppServerModuleNgFactory,
        providers: [provider]
    })
);

app.set('view engine', 'html');
app.set('views', __dirname);

app.use(express.static(__dirname + '/assets', { index: false }));
app.use(express.static(__dirname + '/dist', { index: false }));


app.get('/*', (req, res) => {
    console.time(`GET: ${req.originalUrl}`);
    res.render('./dist/index', {
        req: req,
        res: res,
        providers: [
            {
                provide: 'REQUEST', useValue: (req)
            },
            {
                provide: 'RESPONSE', useValue: (res)
            }
        ]
    });
    console.timeEnd(`GET: ${req.originalUrl}`);
});

app.listen(process.env.PORT || 3000, () => {});

```

**Comment by mike-suggitt** [comment]
As mentioned above the request object is currently being injected into my angular code e.g.
```
constructor(private configService: ConfigService,
                private cookieService: CookieService,
                private redirectionService: RedirectionService, @Inject(REQUEST) private request: Request,
                @Inject(RESPONSE) private response: Response,
                @Inject(PLATFORM_ID) private platformId: string) {
```

**Comment by paulelieskwirrel** [comment]
@mike-suggitt Yeah it was the same issue for me, with code from docs. I can only suggest you to try with my snippet and see if it's feet for u..

**Comment by mike-suggitt** [comment]
ok thanks @paulelieskwirrel i'll look to give it a go

**Comment by mike-suggitt** [comment]
Found the offending code. For some reason the backgroundcookieservice is trying to set cookie values directly against express headers object which is not correct for express as `res.headers` doesn't exist. The express response passed into angular is correct but doesn't have the "incorrect" headers property. It instead uses `getHeaders()` so @paulelieskwirrel your original code would work with the simple addition of `res.headers = res.getHeaders()` prior to calling the render function. This should probably be a bug to be honest as it's not expected behaviour

**Comment by that70schris** [comment]
it looks like `CookieBackendService` is actually really broken. `set cookieString(val: string)` is expecting cookies in express to work the same way they do in the browser where `document.cookie = "foo=bar"` creates a new cookie.  However this is not the case, `this.request.headers.cookie = val;` just overwrites what was already there and `this.request.header.cookie` is a function.  I've submitted #82 which I'm using in a custom `CookieBackendService` which works well.  open to other suggestions

**Comment by rkajbaf** [comment]
What I see with 4.1.2 is that `CookieBackendService` tries to set `this.response.cookie` to a string, but coming from express it is actually a function that sets the cookie.  basically, no way it actually works as constructed.
