### ISSUE TITLE
 Uncaught (in promise): Error: No provider for t!

### ISSUE THREAD

**Issue by kudsyf** [salemdar/ngx-cookie#7]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
am getting this error only when build for production 

> ERROR Error: Uncaught (in promise): Error: No provider for t!
> Error: No provider for t!
>     at S (vendor.8a7e477….bundle.js:207)
>     at T (vendor.8a7e477….bundle.js:207)
>     at t._throwOrNull (vendor.8a7e477….bundle.js:354)
>     at t._getByKeyDefault (vendor.8a7e477….bundle.js:354)
>     at t._getByKey (vendor.8a7e477….bundle.js:354)
>     at t.get (vendor.8a7e477….bundle.js:354)
>     at n.get [as _SiteAuth_85] (main.3ea622e….bundle.js:1)
>     at n.get [as _RouteGuard_86] (main.3ea622e….bundle.js:1)
>     at n.getInternal (main.3ea622e….bundle.js:1)
>     at n.t.get (vendor.8a7e477….bundle.js:368)
>     at S (vendor.8a7e477….bundle.js:207)
>     at T (vendor.8a7e477….bundle.js:207)
>     at t._throwOrNull (vendor.8a7e477….bundle.js:354)
>     at t._getByKeyDefault (vendor.8a7e477….bundle.js:354)
>     at t._getByKey (vendor.8a7e477….bundle.js:354)
>     at t.get (vendor.8a7e477….bundle.js:354)
>     at n.get [as _SiteAuth_85] (main.3ea622e….bundle.js:1)
>     at n.get [as _RouteGuard_86] (main.3ea622e….bundle.js:1)
>     at n.getInternal (main.3ea622e….bundle.js:1)
>     at n.t.get (vendor.8a7e477….bundle.js:368)
>     at c (polyfills.5aae015….bundle.js:43)
>     at c (polyfills.5aae015….bundle.js:43)
>     at polyfills.5aae015….bundle.js:43
>     at t.invokeTask (polyfills.5aae015….bundle.js:36)
>     at Object.onInvokeTask (vendor.8a7e477….bundle.js:368)
>     at t.invokeTask (polyfills.5aae015….bundle.js:36)
>     at r.runTask (polyfills.5aae015….bundle.js:36)
>     at o (polyfills.5aae015….bundle.js:36)
>     at <anonymous>

@angular/cli: 1.0.2
@angular : 4.1.1

and i followed the last documentation steps

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-cookie version:** 1.0.0

* **Angular version:** 4.1.1
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by drosi94** [comment]
Same thing 
ngx-cookie version: 1.0.0

Angular version: 4.0.0

**Comment by jamilalisgandarov** [comment]
**Check this**  -  https://github.com/salemdar/angular2-cookie/issues/37

**Comment by drosi94** [comment]
OK I found the reason, webstorm auto import adds import {...} from 'ngx-cooke/dist' but should be 'ngx-cookie'

**Comment by ShinDarth** [comment]
same here, using Angular 4.4.6 and cli 1.4.9

**Comment by ShinDarth** [comment]
**UPDATE**: the problem is only with `aot` mode. If I use `--aot=false` I don't get this issue.
