### ISSUE TITLE
Could not resolve @nguniversal/express-engine/token

### ISSUE THREAD

**Issue by Scoup** [salemdar/ngx-cookie#78]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
Version 4.1.1 breaks when building angular project.
```
ERROR in ../ngx-cookie/ngx-cookie.ts(10,23): Error during template compile of 'CookieBackendService'
  Could not resolve @nguniversal/express-engine/tokens relative to [object Object]..
```
**Reproduction of the problem**
Install the lastest package (4.1.1) and `ng serve` or `ng build`

**Please tell us about your environment:**

* **ngx-cookie version:** 4.1.1

* **Angular version:** 7.0.3

**Comment by alexander-larchenko** [comment]
Same here,

`ERROR in ./node_modules/ngx-cookie/fesm5/ngx-cookie.js
Module not found: Error: Can't resolve '@nguniversal/express-engine/tokens' in '/home/travis/build/EzTexting/spa/node_modules/ngx-cookie/fesm5'
 @ ./node_modules/ngx-cookie/fesm5/ngx-cookie.js 4:0-71`

**Comment by shprink** [comment]
Same, it should be included in `package.json` as a dependency but it is not. 

workaround => add it to your project: `npm i @nguniversal/express-engine -D`

**Comment by almothafar** [comment]
Angular CLI: 

```
[ng]
[ng] ERROR in ./node_modules/ngx-cookie/fesm5/ngx-cookie.js
[ng] Module not found: Error: Can't resolve '@nguniversal/express-engine/tokens' in 'D:\Sources\SPL\mobile-app\node_modules\ngx-cookie\fesm5'
[ng] i ｢wdm｣: Failed to compile.

```

I'm not sure what the changes you made to ask this, I see it is in `package.json` as a dependency but it is maybe the build itself broken? I see it in `peerDependencies` in published version but in `dependencies` in the source file.

**Comment by AlejandroFlorin** [comment]
Same here

**Comment by SayGoodbyeWithSmile** [comment]
> I also encountered this problem when 'ng build'

it needs  'npm install @nguniversal/express-engine',  however  anyone with obsessive-compulsive disorder don't want to install this。

**Comment by MarkoSulamagi** [comment]
> > I also encountered this problem when 'ng build'
> 
> it needs 'npm install @nguniversal/express-engine', however anyone with obsessive-compulsive disorder don't want to install this。

Haha, well said. I installed it on Friday and and haven't been able to sleep since then. :smile:

**Comment by MrCroft** [comment]
@MarkoSulamagi I had `^4.0.2` in package.json, all working fine for me (if I `rm -rf node_modules && npm install`) BUT on someone else's computer (same os, same node & npm versions), cloning the project for the first time, the error appeared. I don't know why, maybe npm cache? Haven't tried `npm ci` though.
Anyway, the solution that actually permitted me to still sleep at night was replacing `^4.0.2` with `4.0.2` in package.json 😁 as I knew that it was working fine when I created the project with 4.0.2. Didn't invest any time in checking in what version it broke.

**Comment by lares83** [comment]
any update about this issue?

**Comment by cacois** [comment]
Still seeing this"

- ngx-cookie: 4.1.2
- angular: 7.2.11

I'd love to get rid of the @nguniversal/express-engine dependency, it serves no purpose when using neither express nor SSR.

**Comment by almothafar** [comment]
to be honest, this project should be Angular CLI compatible, as Angular comes with their devkit, no need for webpack and the headache from it, as devkit of angular save that for you.

The issue has been here from 6 months, but to be honest, I don't care about cookies anymore, prefer local storage for most of my uses.

**Comment by MrCroft** [comment]
@almothafar in my experience, most apps have/need authorization. In order to properly render a protected route on the server (or even an unprotected route that still needs to display some data about the current user), you need that token or whatever you store for authorization. And you don't have localStorage on the server, that's a client-side only mechanism. The only way I see is to use cookies to store stuff like a token, because you need to read and use that token in your request headers while rendering server side as well, not just from the browser.
That being said, I ended up writing my own cookie service long ago, since it's not that hard to do.

**Comment by almothafar** [comment]
Just for the record, I found this alternative: https://github.com/zoomsphere/ngx-store 
Not tested yet, not sure if it is good one or not.

**Comment by mbahiense** [comment]
in my case, I downgraded dependency to version v4.0.2, working now.
``` json
"ngx-cookie": "4.0.2"
```

**Comment by slavede** [comment]
Still an issue, I don't see why this should be mandatory dependency.

**Comment by qurczak** [comment]
> Still an issue, I don't see why this should be mandatory dependency.

Agree. One year has passed since ticked was opened and problem still exists: `ngx-cookie: 4.1.2`.  The quality of JavaScript packets are amazing...

**Comment by simeyla** [comment]
Especially frustrating when you don't even use server side rendering!

**Comment by salemdar** [comment]
Fixed.
