### ISSUE TITLE
Prerender build broken with NullInjector Error

### ISSUE THREAD

**Issue by AlecEJones** [salemdar/ngx-cookie#91]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

Apologies for re-submitting this, but it doesn't seem to have been solved after previous bug reports were closed.

The following error is created during the build:prerender task.

ERROR { Error: StaticInjectorError(AppServerModule)[REQUEST]:
StaticInjectorError(Platform: core)[REQUEST]:
NullInjectorError: No provider for REQUEST!
at NullInjector.get (.../dist/prerender.js:4898:19)

**Expected/desired behavior**
Angular/Universal prerender templates should compile without errors.

**Reproduction of the problem**

The error can be reproduced by installing Angular Universal Starter and ngx-cookie, then adding the CookieBackendService to the AppServerModule providers. 

https://github.com/angular/universal-starter

Providers can be supplied in extraProviders within prerender.ts, but they have no effect on the error. 

**Please tell us about your environment:**

* **ngx-cookie version:** 4.1.2

* **Angular version:** 6.0.0

**Comment by paolobittante** [comment]
Same behaviour for me. 

**Environment:**

* ngx-cookie version: 4.1.2

* Angular version: 7.1.4

**Comment by rafa-as** [comment]
Same here, @salemdar some news about this?

**Comment by Gorniv** [comment]
what is it your prerender.ts?
you don't have a request for prerendering, write use value like this: https://github.com/Angular-RU/angular-universal-starter/blob/6d1e980655a55b2e1651ac5d040aaff80bc8fe8c/prerender.ts#L77

**Comment by AlecEJones** [comment]
Gorniv is correct, and I managed to resolve my issue. Please follow his link for a resolution.

Instead of injecting 'REQUEST' and 'RESPONSE' as strings (per the ngx-cookie docs), you have to inject REQUEST AND RESPONSE tokens imported from @nguniversal/express-engine/tokens.

The current ngx-cookie docs are are flawed and need to be updated, but that solves the mystery. I can submit a pull request.
